# Installation file for Arch Linux packages

post_install() {
    echo "Configuring comm-hyprland after installation..."

    # Verifica se a dependência ml4w-hyprland está instalada
    if pacman -Q ml4w-hyprland &>/dev/null; then
        echo "Executing ml4w-hyprland-setup..."
        ml4w-hyprland-setup -p arch
    else
        echo "Warning: ml4w-hyprland is not installed. Skipping ml4w-hyprland-setup execution."
    fi
}

post_upgrade() {
    post_install
}